networks:
    gorisfood-network:
        driver: bridge
        
services:
    gorisfood-mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - gorisfood-network
        
    gorisfood-api:
        image: felipefcg/gorisfood-api
        command: ["/wait-for-it.sh", "gorisfood-mysql:3306", "-t", "30", "--", "java", "-jar", "gorisfood-api.jar"]
        environment:
            DB_HOST: gorisfood-mysql
# Removendo a propriedade para nã ter conflito de portas no host, pois vamos escalar a imgem
# durante a execução do docker compose, com o atributo "--scale gorisfood-api=2"             
#        ports: 
#            - "8080:8080"
        networks:
            - gorisfood-network
        depends_on:
            - gorisfood-mysql
            
    gorisfood-proxy:
        build: ./nginx
        image: gorisfood-proxy
        ports:
            - "80:80"
        networks:
            - gorisfood-network
        depends_on:
            - gorisfood-api