server:
  port: 8081

#spring:
#  redis:
#    host: localhost
#    port: 6379
#    password: 

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG   
    
gorisfood:
  jwt:
    keystore:
      path: keystores/gorisfood.jks
      password: 123456
      keypair-alias: gorisfood    