server:
  port: 8081

spring:
#  redis:
#    host: localhost
#    port: 6379
#    password: 
  datasource:
    url: jdbc:mysql://localhost:3306/gorisfood?connectionTimeZone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG   
    
gorisfood:
  jwt:
    keystore:
      path: keystores/gorisfood.jks
      password: 123456
      keypair-alias: gorisfood    